POST http://localhost:8082/api/department
Content-Type: application/json

{
  "description": "test",
  "code": "abc",
  "name": "bla"
}

###

GET http://localhost:8082/api/department/abc


###
POST http://localhost:8081/api/employee
Content-Type: application/json

{
  "email": "abc@abc.ch",
  "firstName": "Marc",
  "lastName": "Müller",
  "departmentCode": "abc"
}

###

GET http://localhost:8081/api/employee/1
